hotel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("staff.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    path('', views.home , name='home'),
    path('insert/', views.insert, name='insert_data'),
    path('insert_data/', views.insert_data, name='insert_data'),
    path('update_details/<id>/', views.update, name='update_details'),
    path('delete/<id>/', views.delete, name='delete'),
]

staff/models.py
from django.db import models

# Create your models here.
class Staff(models.Model):
    image = models.ImageField(upload_to='staff_images')
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    age = models.IntegerField()
    department = models.CharField(max_length=50)
    salary = models.IntegerField()

    def __str__(self):
        return self.fname

staff/views.py
from django.shortcuts import redirect, render

from staff.models import Staff

# Create your views here.
def home(request):
    staff = Staff.objects.all()
    context = {
        'staff':staff
    }
    return render(request, 'home.html',context)

def insert(request):
    return render(request, 'insert_data.html')

def insert_data(request):
    if request.method == 'POST':
        image = request.FILES['image']
        fname = request.POST['fname']
        lname = request.POST['lname']
        age = request.POST['age']
        department = request.POST['department']
        salary = request.POST['salary']

        staff = Staff(
            image = image,
            fname = fname,
            lname = lname,
            age = age,
            department = department,
            salary = salary
        )

        staff.save()
        return redirect('/')

def update(request,id):
    staff = Staff.objects.get(id = id)
    if request.method == 'POST':
        image = request.FILES['image']
        fname = request.POST['fname']
        lname = request.POST['lname']
        age = request.POST['age']
        department = request.POST['department']
        salary = request.POST['salary']
        
        staff.image = image
        staff.fname = fname
        staff.lname = lname
        staff.age = age
        staff.department = department
        staff.salary = salary
        

        staff.save()
        return redirect('/')


    return render(request, 'update_details.html',{'staff':staff})


def delete(request,id):
    staff = Staff.objects.get(id = id)
    staff.delete()
    return redirect('/')

staff/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <!-- <a href="" ></a> -->
    <h1>Homepage is here</h1>
    <table border="1">
      <tr>
        <th>Id</th>
        <th>Image</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Department</th>
        <th>Salary</th>
        <th>Actions</th>
      </tr>
      {% for person in staff %}
      <tr>
        <td>{{person.id}}</td>
        <td>
          <img src="media/{{person.image}}" alt="" width="50"/>
        </td>
        <td>{{person.fname}}</td>
        <td>{{person.lname}}</td>
        <td>{{person.age}}</td>
        <td>{{person.department}}</td>
        <td>{{person.salary}}</td>
        <td>
            <a href="{% url 'staff:update_details' person.id %}">Edit</a>
            <a href="{% url 'staff:delete' person.id %}">Delete</a>
        </td>

      </tr>
      {% endfor %}
    </table>
  </body>
</html>

staff/templates/insert_data.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insert data</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <form action="/insert_data/" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <label for="">upload image</label><br>
        <input type="file" name="image" required><br>
        <input type="text" placeholder="First Name" name="fname" required><br>
        <input type="text" placeholder="Last Name" name="lname" required><br>
        <input type="text" placeholder="Age" name="age" required><br>
        <input type="text" placeholder="Department" name="department" required><br>
        <input type="text" placeholder="Salary(no comas)" name="salary" required><br>
        <input type="submit" value="Create staff" id="btn">
    </form>
</body>
</html>

staff/templates/update_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insert data</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <label for="">upload image</label><br>
        <input type="file" name="image" value="{{staff.image}}" required><br>
        <input type="text" placeholder="First Name" name="fname" value="{{staff.fname}}" required><br>
        <input type="text" placeholder="Last Name" name="lname" value="{{staff.lname}}" required><br>
        <input type="text" placeholder="Age" name="age" value="{{staff.age}}" required><br>
        <input type="text" placeholder="Department" name="department" value="{{staff.department}}" required><br>
        <input type="text" placeholder="Salary(no comas)" name="salary" value="{{staff.salary}}" required><br>
        <input type="submit" value="Update staff" class="btn">
    </form>
</body>
</html>